function results = analyze_freezing_times()
%% Droplet Freezing Time Analysis
%
% Detects freezing events from droplet contrast signals.
%
% Input:
%   CSV or TXT file generated by analyze_video_droplets_running_average.m
%
% Method:
%   For each droplet, the ContrastStd signal is smoothed using a moving
%   median filter. The freezing time is estimated as the point that best
%   separates the signal into two regimes using a step-detection criterion.
%
% Output:
%   - droplet_freezing_times.txt
%   - droplet_freezing_full_results.csv
%   - Individual plots for each droplet
%
% Author: Jorge H. Melillo

clear; clc; close all;

%% User parameters

smoothingWindow = 5;        % Moving median window size
minimumPoints = 8;          % Minimum number of points required per droplet
minimumSegmentFraction = 0.10; % Minimum fraction of points before/after step

%% Select input file

[inputFile, inputPath] = uigetfile( ...
    {'*.csv;*.txt', 'CSV or TXT files'}, ...
    'Select the droplet metrics file');

if isequal(inputFile, 0)
    error('No file selected.');
end

inputFilename = fullfile(inputPath, inputFile);

%% Detect delimiter

fileText = fileread(inputFilename);
lines = splitlines(string(fileText));
firstLine = lines(1);

nComma = count(firstLine, ",");
nSemi  = count(firstLine, ";");
nTab   = count(firstLine, sprintf('\t'));

if nSemi > nComma && nSemi > nTab
    delimiter = ';';
elseif nTab > nComma && nTab > nSemi
    delimiter = '\t';
else
    delimiter = ',';
end

%% Read table

opts = detectImportOptions(inputFilename, 'Delimiter', delimiter);
opts.VariableNamingRule = 'preserve';

dataTable = readtable(inputFilename, opts);

%% Find required columns automatically

variableNames = string(dataTable.Properties.VariableNames);

dropletColumn = find(contains(lower(variableNames), "droplet") & ...
                     contains(lower(variableNames), "id"), 1);

timeColumn = find(contains(lower(variableNames), "timestart"), 1);

contrastColumn = find(contains(lower(variableNames), "contraststd"), 1);

if isempty(dropletColumn)
    error('Could not find droplet ID column.');
end

if isempty(timeColumn)
    error('Could not find TimeStart_s column.');
end

if isempty(contrastColumn)
    error('Could not find ContrastStd column.');
end

%% Get droplet IDs

dropletIDs = unique(dataTable{:, dropletColumn});
dropletIDs = dropletIDs(~isnan(dropletIDs));

%% Create output folder

outputFolder = fullfile(inputPath, 'DropletFreezingAnalysis');

if ~exist(outputFolder, 'dir')
    mkdir(outputFolder);
end

%% Initialize results

resultsTable = table();

%% Analyze each droplet

for i = 1:numel(dropletIDs)

    dropletID = dropletIDs(i);

    dropletMask = dataTable{:, dropletColumn} == dropletID;

    time_s = double(dataTable{dropletMask, timeColumn});
    contrastStd = double(dataTable{dropletMask, contrastColumn});

    % Sort by time
    [time_s, sortOrder] = sort(time_s);
    contrastStd = contrastStd(sortOrder);

    % Remove invalid values
    valid = ~isnan(time_s) & ~isnan(contrastStd);
    time_s = time_s(valid);
    contrastStd = contrastStd(valid);

    if numel(contrastStd) < minimumPoints
        warning('Droplet %g skipped: not enough points.', dropletID);
        continue;
    end

    %% Smooth signal

    currentWindow = smoothingWindow;

    if numel(contrastStd) < currentWindow
        currentWindow = 3;
    end

    contrastSmooth = movmedian(contrastStd, currentWindow);

    %% Detect step-like transition

    nPoints = numel(contrastSmooth);
    minSegmentPoints = max(3, round(minimumSegmentFraction * nPoints));

    candidateRange = minSegmentPoints:(nPoints - minSegmentPoints);

    stepError = nan(size(candidateRange));

    for j = 1:numel(candidateRange)

        candidateIndex = candidateRange(j);

        signalBefore = contrastSmooth(1:candidateIndex);
        signalAfter  = contrastSmooth(candidateIndex+1:end);

        stepError(j) = ...
            sum((signalBefore - mean(signalBefore)).^2) + ...
            sum((signalAfter  - mean(signalAfter)).^2);
    end

    [~, bestIndex] = min(stepError);

    freezingIndex = candidateRange(bestIndex);

    freezingTime_s = time_s(freezingIndex);
    freezingContrast = contrastStd(freezingIndex);

    %% Save result

    newRow = table( ...
        dropletID, ...
        freezingTime_s, ...
        freezingContrast, ...
        'VariableNames', { ...
        'DropletID', ...
        'FreezingTime_s', ...
        'ContrastStdAtFreezing'});

    resultsTable = [resultsTable; newRow]; %#ok<AGROW>

    %% Plot result

    fig = figure('Visible', 'off', 'Color', 'w');

    plot(time_s, contrastStd, 'o-', 'LineWidth', 1);
    hold on;

    plot(time_s, contrastSmooth, '-', 'LineWidth', 2);

    plot(freezingTime_s, freezingContrast, 'rp', ...
        'MarkerSize', 14, ...
        'MarkerFaceColor', 'r');

    xline(freezingTime_s, '--r', 'Freezing', ...
        'LabelOrientation', 'horizontal', ...
        'LabelVerticalAlignment', 'bottom');

    text(freezingTime_s, freezingContrast, ...
        sprintf('  %.3f s', freezingTime_s), ...
        'FontSize', 10, ...
        'FontWeight', 'bold');

    xlabel('Time (s)');
    ylabel('ContrastStd');
    title(sprintf('Droplet %g - Freezing at %.3f s', ...
        dropletID, freezingTime_s));

    legend( ...
        'Raw data', ...
        'Smoothed data', ...
        'Detected freezing point', ...
        'Location', 'best');

    grid on;

    outputPlot = fullfile(outputFolder, ...
        sprintf('Droplet_%g_freezing.png', dropletID));

    exportgraphics(fig, outputPlot, 'Resolution', 300);

    close(fig);

end

%% Save freezing times

txtOutput = fullfile(outputFolder, 'droplet_freezing_times.txt');

writetable(resultsTable(:, {'DropletID', 'FreezingTime_s'}), ...
    txtOutput, ...
    'Delimiter', '\t');

%% Save full results

csvOutput = fullfile(outputFolder, 'droplet_freezing_full_results.csv');

writetable(resultsTable, csvOutput);

%% Display results

disp('Analysis finished.');
disp(resultsTable);
disp(['Results saved in: ', outputFolder]);

%% Return output

results.resultsTable = resultsTable;
results.outputFolder = outputFolder;

end